-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  profile_text TEXT,
  last_feed_generated_at TIMESTAMPTZ
);
-- Create submitted_urls table  
CREATE TABLE IF NOT EXISTS public.submitted_urls (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
-- Create feed_items table
CREATE TABLE IF NOT EXISTS public.feed_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  url TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submitted_urls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feed_items ENABLE ROW LEVEL SECURITY;
-- Create RLS policies for profiles table
CREATE POLICY "Users can view their own profile"
ON public.profiles FOR SELECT
USING (auth.uid() = id);
CREATE POLICY "Users can create their own profile"
ON public.profiles FOR INSERT
WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile"
ON public.profiles FOR UPDATE
USING (auth.uid() = id);
-- Create RLS policies for submitted_urls table
CREATE POLICY "Users can manage their own submitted URLs"
ON public.submitted_urls FOR ALL
USING (auth.uid() = user_id);
-- Create RLS policies for feed_items table
CREATE POLICY "Users can view their own feed items"
ON public.feed_items FOR SELECT
USING (auth.uid() = user_id);
-- Create indexes for better performance
CREATE INDEX idx_submitted_urls_user_id ON public.submitted_urls(user_id);
CREATE INDEX idx_feed_items_user_id ON public.feed_items(user_id);
CREATE INDEX idx_feed_items_created_at ON public.feed_items(created_at DESC);
CREATE INDEX idx_feed_items_item_type ON public.feed_items(item_type);
